# Generated by Django 4.1.4 on 2023-01-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('Price', models.CharField(max_length=122)),
                ('Desc', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
